E_Com/App_Order/urls.py
from django.urls import path
from App_Order import views
app_name='App_Order'

urlpatterns = [
    path('add/<pk>/',views.add_to_cart,name='add'),
    path('cart/',views.cart_view,name='cart'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),
]

E_Com/App_Payment/urls.py
from App_Payment import views
from django.urls import path


app_name="App_Payment"

urlpatterns = [
    path('cheakout/',views.cheakout,name='cheakout'),
    path('pay/',views.payment,name='payment'),
    path('status/',views.complate,name='complate'),
    path('orders/',views.order_view,name='orders'),
    path('purchase/<val_id>/<tran_id>/',views.purchase,name='purchase'),
]

E_Com/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name ='App_Shop'

urlpatterns = [
   path('',views.home,name='home'), 
   path('product/<int:pk>/',views.ProductDetail.as_view(),name='product_detail'), 
   path('search/',views.search,name='search')
]

E_Com/my_ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('contact/', include('App_Contact.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_Com/App_Payment/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    address = models.TextField(max_length=300,blank=True)
    city = models.CharField(max_length=264,blank=True)
    zip_code = models.CharField(max_length=10,blank=True)
    country = models.CharField(max_length=50,blank=True)
    def __str__(self):
        return f'{self.user.profile.username} Billing Address'

    def is_fully_filled(self):
        fields_names =[f.name for f in self._meta.get_fields()]

        for field_name in fields_names:
            value = getattr(self,field_name)
            if value is None or value =='':
                return False
        return True

    class Meta:
        verbose_name_plural = 'Billing Adrresses'

E_Com/App_Payment/forms.py
from django import forms

from App_Payment.models import BillingAddress


class BillingForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields =['address','city','zip_code','country']

E_Com/App_Payment/views.py
from django.contrib import messages
from App_Payment.forms import BillingForm
from App_Payment.models import BillingAddress
from App_Order.models import Cart, Order
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
#for payment
import requests
from sslcommerz_python.payment import SSLCSession
from decimal import Context, Decimal
import socket


@login_required
def cheakout(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]
    form =BillingForm(instance=saved_address)
    if request.method =="POST":
        form=BillingForm(request.POST,instance=saved_address)
        if form.is_valid():
            form.save()
            form=BillingForm(instance=saved_address)
            messages.info(request,f"Shipping Address Saved!!!")
    order_qs = Order.objects.filter(user=request.user,ordered=False)
    order_items =order_qs[0].orderitems.all()
    order_total= order_qs[0].get_totals()
    return render(request,'App_Payment/cheakout.html',context={'form':form,'order_items':order_items,'order_total':order_total,'saved_address':saved_address})

@login_required
def payment(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]
    if not saved_address.is_fully_filled():
        messages.info(request,f"Please complate Shipping Address!!!")
        return redirect('App_Payment:cheakout')
    
    if not request.user.profile.is_fully_filled():
        messages.info(request,f"Please complate Profile Details!!!")
        return redirect('App_Login:profile')

    store_id = 'mysit6083f1bc9bcf5'
    API_key ='mysit6083f1bc9bcf5@ssl'
    mypayment = SSLCSession(sslc_is_sandbox=True, sslc_store_id=store_id, sslc_store_pass=API_key)

    status_url =request.build_absolute_uri(reverse("App_Payment:complate"))
    mypayment.set_urls(success_url=status_url, fail_url=status_url, cancel_url=status_url, ipn_url=status_url)

    order_qs =Order.objects.filter(user =request.user,ordered=False)
    order_items =order_qs[0].orderitems.all()
    order_items_count =order_qs[0].orderitems.count()
    order_total =order_qs[0].get_totals()
    mypayment.set_product_integration(total_amount=Decimal(order_total), currency='BDT', product_category='Mixed', product_name=order_items, num_of_item=order_items_count, shipping_method='Courier', product_profile='None')

    current_user=request.user
    mypayment.set_customer_info(name=current_user.profile.full_name, 
    email=current_user.email, 
    address1=current_user.profile.address_1, 
    address2=current_user.profile.address_1, 
    city=current_user.profile.city, 
    postcode=current_user.profile.zip_code, 
    country=current_user.profile.country, 
    phone=current_user.profile.phone,)

    mypayment.set_shipping_info(shipping_to=current_user.profile.full_name, 
    address=saved_address.address, 
    city=saved_address.city, 
    postcode=saved_address.zip_code, 
    country=saved_address.country)

    response_data = mypayment.init_payment()
    print(response_data)
    return redirect(response_data['GatewayPageURL'])

@csrf_exempt
def complate(request):
    if request.method =='POST' or request.method =='post':
        payment_data =request.POST
        status = payment_data['status']
        if status =="VALID":
            val_id = payment_data['val_id']
            tran_id = payment_data['tran_id']
            messages.success(request,f"Your Payment complate Successfully!!")
            return HttpResponseRedirect(reverse("App_Payment:purchase", kwargs={'val_id':val_id,'tran_id':tran_id,}))
        elif status =="FAILED":
            messages.success(request,f"Your Payment Failed!!Please Try Again!!")
    return render(request,'App_Payment/complate.html',context={'status':status})


@login_required
def purchase(request,val_id,tran_id):
    order_qs =Order.objects.filter(user =request.user,ordered=False)
    order = order_qs[0]
    orderId = tran_id
    order.ordered =True
    order.orderId =orderId
    order.paymentId = val_id
    order.save()
    cart_items=Cart.objects.filter(user =request.user,purchased=False)
    for item in cart_items:
        item.purchased=True
        item.save()
    return HttpResponseRedirect(reverse("App_Shop:home"))

@login_required
def order_view(request):
    try:
        orders=Order.objects.filter(user =request.user,ordered=True)
        context={'orders':orders}
    except:
        messages.warning(request,"You do no Have any active order")
        return redirect('App_Shop:home')
    return render(request,"App_Payment/order.html",context)

E_Com/templates/App_Payment/cheakout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Cheak Out{% endblock %}
{% block css %}
<style>
.card {
    max-width: 1000px;
    margin: 2vh
}

.card-top {
    padding: 0.7rem 5rem
}

.card-top a {
    float: left;
    margin-top: 0.7rem
}

#logo {
    font-family: 'Dancing Script';
    font-weight: bold;
    font-size: 1.6rem
}

.card-body {
    padding: 0 5rem 5rem 5rem;
    background-image: url("https://i.imgur.com/4bg1e6u.jpg");
    background-size: cover;
    background-repeat: no-repeat
}

@media(max-width:768px) {
    .card-body {
        padding: 0 1rem 1rem 1rem;
        background-image: url("https://i.imgur.com/4bg1e6u.jpg");
        background-size: cover;
        background-repeat: no-repeat
    }

    .card-top {
        padding: 0.7rem 1rem
    }
}

.row {
    margin: 0
}

.upper {
    padding: 1rem 0;
    justify-content: space-evenly
}

#three {
    border-radius: 1rem;
    width: 22px;
    height: 22px;
    margin-right: 3px;
    border: 1px solid blue;
    text-align: center;
    display: inline-block
}

#payment {
    margin: 0;
    color: blue
}

.icons {
    margin-left: auto
}

form span {
    color: rgb(179, 179, 179)
}

form {
    padding: 2vh 0
}

input {
    border: 1px solid rgba(0, 0, 0, 0.137);
    padding: 1vh;
    margin-bottom: 4vh;
    outline: none;
    width: 100%;
    background-color: rgb(247, 247, 247)
}

input:focus::-webkit-input-placeholder {
    color: transparent
}

.header {
    font-size: 1.5rem
}

.left {
    background-color: #ffffff;
    padding: 2vh
}

.left img {
    width: 2rem
}

.left .col-4 {
    padding-left: 0
}

.right .item {
    padding: 0.3rem 0
}

.right {
    background-color: #ffffff;
    padding: 2vh
}

.col-8 {
    padding: 0 1vh
}

.lower {
    line-height: 2
}

.btn {
    background-color: rgb(23, 4, 189);
    border-color: rgb(23, 4, 189);
    color: white;
    width: 100%;
    font-size: 0.7rem;
    margin: 4vh 0 1.5vh 0;
    padding: 1.5vh;
    border-radius: 0
}

.btn:focus {
    box-shadow: none;
    outline: none;
    box-shadow: none;
    color: white;
    -webkit-box-shadow: none;
    
    transition: none
}

.btn:hover {
    color: white
}

a {
    color: black
}

a:hover {
    color: black;
    text-decoration: none
}

input[type=checkbox] {
    width: unset;
    margin-bottom: unset
}

#cvv {
    background-image: linear-gradient(to left, rgba(255, 255, 255, 0.575), rgba(255, 255, 255, 0.541)), url("https://img.icons8.com/material-outlined/24/000000/help.png");
    background-repeat: no-repeat;
    background-position-x: 95%;
    background-position-y: center
}
.img-fluid {
    width: 75px;
    height: 75px;
}

</style>  
{% endblock %}
{% block body %}
<div class="container">
<div class="card">
    <div class="card-top border-bottom text-center"> <a href="{% url 'App_Shop:home' %}"> Back to shop</a> <span id="logo">BBBootstrap.com</span> </div>
    <div class="card-body">
        <div class="row upper"> <span><i class="fa fa-check-circle-o"></i> Shopping bag</span> <span><i class="fa fa-check-circle-o"></i> Order details</span> <span id="payment"><span id="three">3</span>Payment</span> </div>
        <div class="row">
            <div class="col-md-7">
                <div class="left border">
                    <div class="row"> <span class="header">Payment</span>
                        <div class="icons"> <img src="https://img.icons8.com/color/48/000000/visa.png" /> <img src="https://img.icons8.com/color/48/000000/mastercard-logo.png" /> <img src="https://img.icons8.com/color/48/000000/maestro.png" /> </div>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        {{form|crispy}} 
                        <input type="submit" class="btn" value="Saved Address">
                    </form>
                </div>
            </div>
            <div class="col-md-5">
                <div class="right border">
                    <div class="header">Order Summary</div>
                    <div class="row item">
                    {% for order_item in order_items %}
                    <div class="col-4 align-self-center"><img class="img-fluid" src="/media/{{ order_item.item.image}}"></div>
                        <div class="col-8">
                            <div class="row"><b>{{ order_item.item.price|floatformat:2}} X {{ order_item.quantity}}
                            </b></div>
                            <div class="row text-muted">{{ order_item.item.name}}</div>
                            <div class="row">Qty:{{ order_item.quantity}}</div>
                            <hr>
                        </div>   
                    {% endfor %}  
                    </div> 
                    <hr>
                    <div class="row lower">
                        <div class="col text-left">Subtotal</div>
                        <div class="col text-right">&#2547;{{ order_total|floatformat:2}}</div>
                    </div>
                    <div class="row lower">
                        <div class="col text-left">Delivery</div>
                        <div class="col text-right">Free</div>
                    </div>
                    <div class="row lower">
                        <div class="col text-left"><b>Total to pay</b></div>
                        <div class="col text-right"><b>&#2547;{{ order_total|floatformat:2}}</b></div>
                    </div>
                    <div class="row lower"> 
                        {% if saved_address.is_fully_filled %}
                        <a href="{% url 'App_Payment:payment' %}" class="btn">
                             Make Payment
                        </a>
                        {% else %}
                        <div class="alert alert-primary" role="alert">
                            <p>Please fill up all the information to make Payment.</p>
                        </div>   
                        {% endif %}   
                    </div> 
                    <p class="text-muted text-center">Complimentary Shipping & Returns</p>
                </div>
            </div>
        </div>
    </div>
    <div> </div>
</div>
</div>   
{% endblock %}

E_Com/templates/App_Payment/complate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Cheak Out{% endblock %}
{% block css %}
<style>
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap");

.cart {
    height: 100vh
}

.progresses {
    display: flex;
    align-items: center
}

.line {
    width: 76px;
    height: 6px;
    background: #63d19e
}
.line1 {
    width: 76px;
    height: 6px;
    background: red;
}

.steps {
    display: flex;
    background-color: #63d19e;
    color: #fff;
    font-size: 12px;
    width: 30px;
    height: 30px;
    align-items: center;
    justify-content: center;
    border-radius: 50%
}
.steps1 {
    display: flex;
    background-color: red;
    color: #fff;
    font-size: 12px;
    width: 30px;
    height: 30px;
    align-items: center;
    justify-content: center;
    border-radius: 50%
}

.check1 {
    display: flex;
    background-color: #63d19e;
    color: #fff;
    font-size: 17px;
    width: 60px;
    height: 60px;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    margin-bottom: 10px
}
.check2 {
    display: flex;
    background-color: red;
    color: #fff;
    font-size: 17px;
    width: 60px;
    height: 60px;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    margin-bottom: 10px
}
.invoice-link {
    font-size: 15px
}

.order-button {
    height: 40px
}

.background-muted {
    background-color: #fafafc
}
</style>
{% endblock %}
{% block body %}
<div class="container mt-4 mb-4">
    <div class="row d-flex cart align-items-center justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="d-flex justify-content-center border-bottom">
                    <div class="p-3">
                        <div class="progresses">
                            {% if status == "FAILED" %}
                            <div class="steps1"> <span><i class="fa fa-times"></i></span> </div> <span class="line1"></span>
                            <div class="steps1"> <span><i class="fa fa-times"></i></span> </div> <span class="line1"></span>
                            <div class="steps1"> <span class="font-weight-bold">3</span> </div>
                            {% else %}
                            
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row g-0">
                    <div class="col-md-6 border-right p-5">
                        <div class="text-center order-details">
                            <div class="d-flex justify-content-center mb-5 flex-column align-items-center"> 
                                {% if status == "FAILED" %}
                                <span class="check2"><i class="fa fa-times"></i></span> 
                                <span class="font-weight-bold">Order Canceled</span> 
                                <small class="mt-2">Your illustraion will go to you soon</small> 
                                <a href="{% url 'App_Order:cart' %}" class="btn btn-danger btn-block order-button mt-5">Go to your Cart</a> 
                                {% else %}
                                
                                {% endif %}
                                    
                                
                            </div> 
                            
                        </div>
                    </div>
                    <div class="col-md-6 background-muted">
                        <div class="p-3 border-bottom">
                            <div class="d-flex justify-content-between align-items-center"> <span><i class="fa fa-clock-o text-muted"></i> 3 days delivery</span> <span><i class="fa fa-refresh text-muted"></i> 2 Max Revisions</span> </div>
                            <div class="mt-3">
                                <h6 class="mb-0">Illustraion in Sketch or AI</h6> <span class="d-block mb-0">Includes: Sketch, PSD, PNG, SVG, AI </span> <small>Min: 1 illustraion</small>
                                <div class="d-flex flex-column mt-3"> <small><i class="fa fa-check text-muted"></i> Vector file</small> <small><i class="fa fa-check text-muted"></i> Sources files</small> </div>
                            </div>
                        </div>
                        <div class="row g-0 border-bottom">
                            <div class="col-md-6 border-right">
                                <div class="p-3 d-flex justify-content-center align-items-center"> <span>x3</span> </div>
                            </div>
                            <div class="col-md-6">
                                <div class="p-3 d-flex justify-content-center align-items-center"> <span>$20 per unit</span> </div>
                            </div>
                        </div>
                        <div class="row g-0 border-bottom">
                            <div class="col-md-6">
                                <div class="p-3 d-flex justify-content-center align-items-center"> <span>Subtotal</span> </div>
                            </div>
                            <div class="col-md-6">
                                <div class="p-3 d-flex justify-content-center align-items-center"> <span>$60</span> </div>
                            </div>
                        </div>
                        <div class="row g-0 border-bottom">
                            <div class="col-md-6">
                                <div class="p-3 d-flex justify-content-center align-items-center"> <span>Processing fees</span> </div>
                            </div>
                            <div class="col-md-6">
                                <div class="p-3 d-flex justify-content-center align-items-center"> <span>$1.80</span> </div>
                            </div>
                        </div>
                        <div class="row g-0">
                            <div class="col-md-6">
                                <div class="p-3 d-flex justify-content-center align-items-center"> <span class="font-weight-bold">Total</span> </div>
                            </div>
                            <div class="col-md-6">
                                <div class="p-3 d-flex justify-content-center align-items-center"> <span class="font-weight-bold">$61.80</span> </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div> </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}
    

E_Com/templates/App_Payment/order.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title %} Orders {% endblock %}
{% block css %}
<style>
.contact-image{
    text-align: center;
}
.contact-image img{
    border-radius: 6rem;
    width: 11%;
    margin-top: -3%;
    transform: rotate(29deg);
}
.contact-form{
    background: #fff;
    margin-top: 10%;
    margin-bottom: 5%;
    width: 100%;
}
</style>
{% endblock %}
{% block body %}
<div class="contact-form">
    <div class="contact-image">
        <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
    </div>
 <h2 class="text-center"><strong>Your Order</strong></h2>
 <div class="row">
     <div class="col-md-12">
         <div class="card mt-5" style="height: auto;">
          <div class="table-responsive">
              <table class="table">
                  <thead>
                      <tr>
                          <th scope="col">#</th>
                          <th scope="col">Order ID</th>
                          <th scope="col">Products</th>
                          <th scope="col">Status</th>
                      </tr>
                  </thead>
                  <tbody>  
                      {% for order in orders %}
                      <tr> 
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="#">{{order.orderId}}</a></td>
                        <td>
                            {% for item in order.orderitems.all %}
                             {{ item }}  
                             <br> 
                            {% endfor %}  
                        </td>
                        <td><span class="badge badge-primary" style="height: 25px; width: 150px; font-size: 12px;">{{ order.status }}</span></td>
                        </tr>   
                      {% endfor %} 
                  </tbody>
              </table>
          </div> 
        </div>
         </div>
         <div class="col-md-12 text-center mt-2">
             <a href="{% url 'App_Shop:home' %}" class="btn btn-primary ">Back To Home</a>
         </div>
     </div>
 </div>

{% endblock %}
    