E_Com/App_Contact/urls.py
from django.urls import path
from App_Contact import views
app_name='App_Contact'

urlpatterns = [
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
]

E_Com/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name ='App_Login'

urlpatterns = [
    path("signup/", views.sign_up, name="signup"),   
    path("login/", views.login_user, name="login"),   
    path("logout/", views.logout_user, name="logout"),   
    path("profile/", views.user_profile, name="profile"),   
    path("edit/", views.user_change, name="edit"),   
    path("password/", views.pass_change, name="password"),     
]

E_Com/App_Order/urls.py
from django.urls import path
from App_Order import views
app_name='App_Order'

urlpatterns = [
    path('add/<pk>/',views.add_to_cart,name='add'),
    path('cart/',views.cart_view,name='cart'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),
]

E_Com/App_Payment/urls.py
from App_Payment import views
from django.urls import path


app_name="App_Payment"

urlpatterns = [
    path('cheakout/',views.cheakout,name='cheakout'),
    path('pay/',views.payment,name='payment'),
    path('status/',views.complate,name='complate'),
    path('orders/',views.order_view,name='orders'),
    path('purchase/<val_id>/<tran_id>/',views.purchase,name='purchase'),
]

E_Com/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name ='App_Shop'

urlpatterns = [
   path('',views.home,name='home'), 
   path('product/<int:pk>/',views.ProductDetail.as_view(),name='product_detail'), 
   path('search/',views.search,name='search')
]

E_Com/my_ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('contact/', include('App_Contact.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_Com/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/13f9557492.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    
    {% block css %}
        
    {% endblock  %}
        
    <title>{% block title %} E-Com Website {% endblock %}</title>
    
</head>
        
<body>
<div class="container" style="padding-top: 15px;">
    <div messages container mt-2>   
        {% if messages %}     
            {% for message in messages %}
              <div {% if message.tags %}   class="alert alert-{{message.tags}}" {% endif %} role="alert">
                {{message}} 
            {% endfor %}  
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>     
        {% endif %}       
            </div>     
    </div>
    {% block body %}
     <div class="container">
         
     </div>   
    {% endblock %}
        
</div>
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

E_Com/templates/navbar.html
{% load cart_tag %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/13f9557492.js"></script>
    
    
    {% block css %}
        
    {% endblock  %}
        
    <title>{% block title %} E-Com Website {% endblock %}</title>
</head>     
<body>
  <div class="messages container mt-2">   
    {% if messages %}     
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
            {{message}} 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
          </div>
        {% endfor %}         
    {% endif %}     
</div>
  <div class="container" >
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <a class="navbar-brand" href="{% url 'App_Shop:home' %}">E-Zone.com</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            
            {% if request.user.is_authenticated %}
   
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'App_Contact:about' %}">About Us <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Contact:contact' %}">Contact Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Payment:orders' %}">Orders</a>
            </li>
            <form method="GET" action="/search/" class="form-inline my-2 my-lg-0" >
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <li class="nav-item ">
              <a class="nav-link " href="{% url 'App_Order:cart' %}">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>Cart
                <span class="badge badge-primary">{{ request.user | cart_total }}</span>
              
              </a>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-user-tie" aria-hidden="true">{{request.user.profile.username}}</i> 
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Change Profile Info</a>
                  <a class="dropdown-item" href="{% url 'App_Login:edit' %}">Change User Info</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                </div>
              </li>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'App_Login:login' %}" class="nav-link btn btn-outline-success">Login</a>
            </li>
            &nbsp;
            <li class="nav-item">
              <a href="{% url 'App_Login:signup' %}" class="nav-link btn btn-outline-success">Signup</a>
            </li>
            {% endif %}  
          </ul> 
        </div>
      </nav>

    
    {% block body %}
        
    {% endblock %}
        
</div>
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>