E_Com/App_Order/urls.py
from django.urls import path
from App_Order import views
app_name='App_Order'

urlpatterns = [
    path('add/<pk>/',views.add_to_cart,name='add'),
    path('cart/',views.cart_view,name='cart'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),
]

E_Com/App_Payment/urls.py
from App_Payment import views
from django.urls import path


app_name="App_Payment"

urlpatterns = [
    path('cheakout/',views.cheakout,name='cheakout'),
    path('pay/',views.payment,name='payment'),
    path('status/',views.complate,name='complate'),
    path('orders/',views.order_view,name='orders'),
    path('purchase/<val_id>/<tran_id>/',views.purchase,name='purchase'),
]

E_Com/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name ='App_Shop'

urlpatterns = [
   path('',views.home,name='home'), 
   path('product/<int:pk>/',views.ProductDetail.as_view(),name='product_detail'), 
   path('search/',views.search,name='search')
]

E_Com/my_ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('contact/', include('App_Contact.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_Com/App_Order/models.py
from django.db import models

from django.conf import settings
from django.db.models.enums import Choices

from App_Shop.models import Product

class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='cart')
    item = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity =models.IntegerField(default=1)
    purchased =models.BooleanField(default=False)
    created =models.DateTimeField(auto_now_add=True)
    updated =models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item}'

    def get_total(self):
        total =self.item.price * self.quantity
        float_total =format(total,'0.2f')
        return float_total


class Order(models.Model):
    orderitems =models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered =models.BooleanField(default=False)
    created =models.DateTimeField(auto_now_add=True)
    status_name=(
        ("Order confirmed","Order confirmed"),
        ("Picked by courier","Picked by courier"),
        ("On the way","On the way"),
        ("Delivered","Delivered"),
        ("Processing Your Order","Processing Your Order")
    )
    status =models.CharField(choices=status_name,default="Processing Your Order",max_length=50)
    paymentId =models.CharField(max_length=264,blank=True,null=True)
    orderId =models.CharField(max_length=264,blank=True,null=True)

    def get_totals(self):
        total =0
        for order_item in self.orderitems.all():
            total +=float(order_item.get_total())
        return total

E_Com/App_Order/views.py
from django.contrib import messages
from App_Order.models import Cart, Order
from App_Shop.models import Product
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def add_to_cart(request,pk):
    item =get_object_or_404(Product,pk=pk)
    order_item =Cart.objects.get_or_create(item=item,user=request.user,purchased=False)
    order_qs =Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order =order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity +=1
            order_item[0].save()
            messages.info(request,"This Item Quantity was Updated.")
            return redirect("App_Shop:home")
        else:
            order.orderitems.add(order_item[0])
            messages.info(request,"This Item added to your Cart.")
            return redirect("App_Shop:home")
    else:
        order =Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request,"This Item added to your Cart.")
        return redirect("App_Shop:home")


@login_required
def cart_view(request):
    carts= Cart.objects.filter(user=request.user,purchased=False)
    orders= Order.objects.filter(user=request.user,ordered=False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request,'App_Order/cart.html',context={'carts':carts,'order':order})
    else:
        messages.warning(request,"You Don't have any Item in your Cart")
        return redirect('App_Shop:home')


@login_required
def remove_from_cart(request,pk):
    item = get_object_or_404(Product,pk=pk)
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order =order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item= Cart.objects.filter(item=item,user=request.user,purchased=False)[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            messages.info(request,"This Item was remove from your Cart.")
            return redirect('App_Order:cart')
        else:
            messages.info(request,"This Item was not in your Cart.")
            return redirect('App_Shop:home')  
    else:
        messages.info(request,"You Don't have any active Order.")
        return redirect('App_Shop:home')

@login_required
def increase_cart(request,pk):
    item = get_object_or_404(Product,pk=pk)
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order =order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item= Cart.objects.filter(item=item,user=request.user,purchased=False)[0]
            if order_item.quantity>=1:
                order_item.quantity +=1
                order_item.save()
                messages.info(request,f"{item.name} Quantity has been Updated")
                return redirect('App_Order:cart')
        else:
            messages.info(request,"This Item was not in your Cart.")
            return redirect('App_Shop:home')  
    else:
        messages.info(request,"You Don't have any active Order.")
        return redirect('App_Shop:home')

@login_required
def decrease_cart(request,pk):
    item = get_object_or_404(Product,pk=pk)
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order =order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item= Cart.objects.filter(item=item,user=request.user,purchased=False)[0]
            if order_item.quantity>1:
                order_item.quantity -=1
                order_item.save()
                messages.info(request,f"{item.name} Quantity has been Updated")
                return redirect('App_Order:cart')
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.info(request,f"{item.name} was remove from your Cart.")
                return redirect('App_Shop:home')
        else:
            messages.info(request,"This Item was not in your Cart.")
            return redirect('App_Shop:home')  
    else:
        messages.info(request,"You Don't have any active Order.")
        return redirect('App_Shop:home')

E_Com/templates/App_Order/cart.html
{% extends 'navbar.html' %}
{% block title %} Cart {% endblock %}
{% block css %} 
<style>
.bloc_left_price {
    color: #c01508;
    text-align: center;
    font-weight: bold;
    font-size: 150%;
}
.category_block li:hover {
    background-color: #007bff;
}
.category_block li:hover a {
    color: #ffffff;
}
.category_block li a {
    color: #343a40;
}
.add_to_cart_block .price {
    color: #c01508;
    text-align: center;
    font-weight: bold;
    font-size: 200%;
    margin-bottom: 0;
}
.add_to_cart_block .price_discounted {
    color: #343a40;
    text-align: center;
    text-decoration: line-through;
    font-size: 140%;
}
.product_rassurance {
    padding: 10px;
    margin-top: 15px;
    background: #ffffff;
    border: 1px solid #6c757d;
    color: #6c757d;
}
.product_rassurance .list-inline {
    margin-bottom: 0;
    text-transform: uppercase;
    text-align: center;
}
.product_rassurance .list-inline li:hover {
    color: #343a40;
}
.reviews_product .fa-star {
    color: gold;
}
.pagination {
    margin-top: 20px;
}
</style>
{% endblock %}
{% block body %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">E-Zone.com CART</h1>
     </div>
</section>

<div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Product</th>
                            <th scope="col">Available</th>
                            <th scope="col" class="text-center">Quantity</th>
                            <th scope="col" class="text-right">Price</th>
                            <th scope="col" class="text-right">Remove</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart in carts %}
                        <tr>
                            <td><img src="/media/{{ cart.item.image}}" style="height: 50px;width: 50px;"/> </td>
                            <td>{{cart.item.name}}</td>
                            <td>In stock</td>
                            <td><a href="{% url 'App_Order:decrease' pk=cart.item.pk %}"><span class="badge badge-light"><i class="fa fa-minus" aria-hidden="true"></i></span></a>
                            {{cart.quantity}}
                            <a href="{% url 'App_Order:increase' pk=cart.item.pk %}"><span class="badge badge-light"><i class="fa fa-plus" aria-hidden="true"></i></span></a></td>
                            <td class="text-right">&#2547 {{ cart.get_total}}</td>
                            <td class="text-right"><a href="{% url 'App_Order:remove' pk=cart.item.pk %}"><button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button></a>
                            </td>
                        </tr>
                            
                        {% endfor %}   
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Sub-Total</td>
                            <td class="text-right">&#2547 {{ order.get_totals|floatformat:2}}</td>
                        </tr>
                        
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Total</strong></td>
                            <td class="text-right"><strong>&#2547 {{ order.get_totals|floatformat:2}}</strong></td>
                        </tr> 
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                    <a href="{% url 'App_Shop:home' %}">
                        <button class="btn btn-block btn-light">Continue Shopping</button>
                    </a>
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                    <a href="{% url 'App_Payment:cheakout' %}">
                        <button class="btn btn-lg btn-block btn-success text-uppercase">Checkout</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}