E_Com/App_Order/urls.py
from django.urls import path
from App_Order import views
app_name='App_Order'

urlpatterns = [
    path('add/<pk>/',views.add_to_cart,name='add'),
    path('cart/',views.cart_view,name='cart'),
    path('remove/<pk>/',views.remove_from_cart,name='remove'),
    path('increase/<pk>/',views.increase_cart,name='increase'),
    path('decrease/<pk>/',views.decrease_cart,name='decrease'),
]

E_Com/App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name ='App_Shop'

urlpatterns = [
   path('',views.home,name='home'), 
   path('product/<int:pk>/',views.ProductDetail.as_view(),name='product_detail'), 
   path('search/',views.search,name='search')
]

E_Com/my_ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('', include('App_Shop.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('contact/', include('App_Contact.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

E_Com/App_Shop/models.py
from django.db import models

class Product(models.Model):
    image =models.ImageField(upload_to='Products')
    name =models.CharField(max_length=264)
    category =models.CharField(max_length=50,default="")
    preview_text =models.TextField(max_length=200,verbose_name='Preview Text')
    detail_text =models.TextField(max_length=1000,verbose_name='Discription')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering =['-created']

E_Com/App_Shop/views.py
from django.views.generic import DetailView
from App_Shop.models import Product
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse,HttpResponseRedirect
from math import ceil
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
# Create your views here.

def home(request):
    allProds=[]
    catprods= Product.objects.values('category')
    cats= {item["category"] for item in catprods}
    for cat in cats:
        prod=Product.objects.filter(category=cat)
        n = len(prod)
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        allProds.append([prod, range(1, nSlides), nSlides])
        params={'allProds':allProds }
    return render(request,'App_Shop/home.html', params)

def searchMatch(query, item):
    '''return true only if query matches the item'''
    if query in item.detail_text.lower() or query in item.name.lower() or query in item.category.lower():
        return True
    else:
        return False


def search(request):
    query = request.GET.get('search','')
    allProds = []
    catprods = Product.objects.values('category', 'id')
    cats = {item['category'] for item in catprods}
    for cat in cats:
        prodtemp = Product.objects.filter(category=cat)
        prod = [item for item in prodtemp if searchMatch(query, item)]

        n = len(prod)
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        if len(prod) != 0:
            allProds.append([prod, range(1, nSlides), nSlides])
    params = {'allProds': allProds}
    if len(allProds) == 0 or len(query)<4:
        messages.warning(request,"Please make sure to enter relevant search query")
    return render(request,'App_Shop/home.html', params)


class ProductDetail(LoginRequiredMixin,DetailView):
    model = Product
    template_name='App_Shop/product_detail.html'
  

E_Com/templates/App_Shop/home.html
{% extends 'navbar.html' %}
{% block title %} E-Com Homepage  {% endblock %}
{% block css %}
 <style>
.col-md-3{
    display: inline-block;
    margin-left: -4px;
}
.col-md-3 img{
    width: 260px;
    height: 242px;
}
.carousel-indicators li{
    background-color: blue;
}
.carousel-indicators {
    bottom: 0;
}
.carousel-indicators .active{
    background-color: blue;
}
.carousel-control-prev-icon,
.carousel-control-next-icon{
    background-color: blue;
}
.no-padding{
    padding-right: 0;
    padding-left: 0;
}
 
 </style>       
{% endblock  %}
{% block body %}  
<!-- Indicators -->
{% for product, range, nSlides in allProds %}
    <h5 class="my-4">Flash Sale On {{product.0.category}} - Recommended Items</h5>
<div id="demo{{forloop.counter}}" class="carousel slide my-3" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

       {% for i in range %}
      <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" ></li>
      {% endfor %}
    </ul>
    <div class="container carousel-inner no-padding">
      <div class="carousel-item active">
        {% for i in product %}
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="card" style="width: 18rem; height: 360px;">
                <img src='/media/{{i.image}}' class="card-img-top" alt="...">
                <div class="card-body">
                  <a href="{% url 'App_Shop:product_detail' pk=i.pk %}"><h5 class="card-title">{{i.name}}</h5></a>  
                  <strong><span>&#2547; {{ i.price|floatformat:2}}</span></strong>
                  <strike><span>&#2547; {{ i.old_price|floatformat:2}}</span></strike>
                   
                </div>
              </div>
            </div>
            
            {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
             </div>
             <div class="carousel-item">
            {% endif%}

            {% endfor %}
      </div>

      </div>
    </div>

<a class="carousel-control-prev " href="#demo{{forloop.counter}}" role="button" data-slide="prev">
   <span class="carousel-control-prev-icon" aria-hidden="true" ></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#demo{{forloop.counter}}" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
    {% endfor %}
{% endblock %}

E_Com/templates/App_Shop/product_detail.html
{% extends 'navbar.html' %}
{% block title %} Product Detail Page  {% endblock %}
{% block css %}
<style>
img {
  height: 300px;
  width: 250px; }

.preview {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

.preview-pic {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.preview-thumbnail.nav-tabs {
  border: none;
  margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
    .preview-thumbnail.nav-tabs li img {
      max-width: 100%;
      display: block; }
    .preview-thumbnail.nav-tabs li a {
      padding: 0;
      margin: 0; }
    .preview-thumbnail.nav-tabs li:last-of-type {
      margin-right: 0; }

.tab-content {
  overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
            animation-name: opacity;
    -webkit-animation-duration: .3s;
            animation-duration: .3s; }

.card {
  margin-top: 50px;
  background: #eee;
  padding: 3em;
  line-height: 1.5em; }

@media screen and (min-width: 997px) {
  .wrapper {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; } }

.details {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }

.colors {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.product-title, .price, .sizes, .colors {
  text-transform: UPPERCASE;
  font-weight: bold; }

.checked, .price span {
  color: #ff9f1a; }

.product-title, .rating, .product-description, .price, .vote, .sizes {
  margin-bottom: 15px; }

.product-title {
  margin-top: 0; }

.size {
  margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

.color {
  display: inline-block;
  vertical-align: middle;
  margin-right: 10px;
  height: 2em;
  width: 2em;
  border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

.add-to-cart, .like {
  background: #ff9f1a;
  padding: 1.2em 1.5em;
  border: none;
  text-transform: UPPERCASE;
  font-weight: bold;
  color: #fff;
  -webkit-transition: background .3s ease;
          transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: #b36800;
    color: #fff; }

.not-available {
  text-align: center;
  line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

.orange {
  background: #ff9f1a; }

.green {
  background: #85ad00; }

.blue {
  background: #0076ad; }

.tooltip-inner {
  padding: 1.3em; }

@-webkit-keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

@keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }
</style>
{% endblock %}
{% block body %}
<div class="card">
    <div class="container-fliud">
        <div class="wrapper row">
            <div class="preview col-md-6">    
                <div class="preview-pic tab-content">
                  <div class="tab-pane active" id="pic-1"><img src="/media/{{ object.image}}" /></div>    
                </div>    
            </div>
            <div class="details col-md-6">
                <h3 class="product-title">{{ object.name }}</h3>
                <h4 class="price">current price: <span>BDT &#2547;{{ object.price}}</span></h4>
                <h4 class="price">Previous price: <span><strike>BDT &#2547;{{ object.old_price}}</strike></span></h4>
                <p class="product-description">{{ object.detail_text|linebreaks}}</p>
                <div class="action">
                    <a href="{% url 'App_Order:add' pk=object.pk %}">
                      <button class="add-to-cart btn btn-default" type="button"><i class="fa fa-shopping-cart" aria-hidden="true"> Add To Cart</i></button>
                    </a>
                    
                </div>
            </div>
        </div>
    </div>
</div> 


{% endblock %}
    

E_Com/templates/App_Shop/search.html
{% extends 'navbar.html' %}
{% block title %}
    
{% endblock %}
{% block css %}
<style>
    .col-md-3{
        display: inline-block;
        margin-left: -4px;
    }
    .col-md-3 img{
        width: 260px;
        height: 242px;
    }
    .carousel-indicators li{
        background-color: blue;
    }
    .carousel-indicators {
        bottom: 0;
    }
    .carousel-indicators .active{
        background-color: blue;
    }
    .carousel-control-prev-icon,
    .carousel-control-next-icon{
        background-color: blue;
    }
    .no-padding{
        padding-right: 0;
        padding-left: 0;
    }
     
     </style>          
{% endblock  %}
{% block body %}
 <!-- Indicators -->
{% for product, range, nSlides in allProds %}
<h5 class="my-4">Flash Sale On {{product.0.category}} - Recommended Items</h5>
<div id="demo{{forloop.counter}}" class="carousel slide my-3" data-ride="carousel">
<ul class="carousel-indicators">
  <li data-target="#demo{{forloop.counter}}" data-slide-to="0" class="active"></li>

   {% for i in range %}
  <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}" ></li>
  {% endfor %}
</ul>
<div class="container carousel-inner no-padding">
  <div class="carousel-item active">
    {% for i in product %}
        <div class="col-xs-12 col-sm-6 col-md-3">
          <div class="card" style="width: 18rem; height: 360px;">
            <img src='/media/{{i.image}}' class="card-img-top" alt="...">
            <div class="card-body">
              <a href="{% url 'App_Shop:product_detail' pk=i.pk %}"><h5 class="card-title">{{i.name}}</h5></a>  
              <strong><span>&#2547; {{ i.price|floatformat:2}}</span></strong>
              <strike><span>&#2547; {{ i.old_price|floatformat:2}}</span></strike>
               
            </div>
          </div>
        </div>
        
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
         </div>
         <div class="carousel-item">
        {% endif%}

        {% endfor %}
  </div>

  </div>
</div>

<a class="carousel-control-prev " href="#demo{{forloop.counter}}" role="button" data-slide="prev">
<span class="carousel-control-prev-icon" aria-hidden="true" ></span>
<span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#demo{{forloop.counter}}" role="button" data-slide="next">
<span class="carousel-control-next-icon" aria-hidden="true"></span>
<span class="sr-only">Next</span>
</a>
{% endfor %}

{% endblock %}
    